/* ============================================================
   Delight Studio — content / data layer
   Product data is rebuilt from the client's real stock export
   (items_Delight_Studio.xlsx) → see lib/catalog.data.ts, which is
   generated by scratchpad/gen_catalog.py. Imagery stays PLACEHOLDER
   stock (/public/images) until the client sends real photos.
   Contact details below are the client's REAL details.
   ============================================================ */

import { CATALOG, CATEGORY_FACETS, NEW_ARRIVAL_SLUGS } from "./catalog.data";

export type NavLink = { label: string; href: string };
export type NavCategory = {
  label: string;
  href: string;
  /* mega-menu columns (only for categories that have subsections) */
  columns?: { heading?: string; links: NavLink[] }[];
};

/* Navbar categories — grouped mega-menus, rebuilt to match the client's real
   stock (sarees · ethnicwear · western · innerwear). Leaf links point at the
   dynamic shop route /shop/[category]. */
export const navCategories: NavCategory[] = [
  { label: "New", href: "/shop/new" },
  { label: "Sarees", href: "/shop/sarees" },
  {
    label: "Ethnicwear",
    href: "/shop/ethnicwear",
    columns: [
      {
        heading: "Kurtis & Suits",
        links: [
          { label: "Kurtis", href: "/shop/kurtis" },
          { label: "Anarkalis", href: "/shop/anarkalis" },
        ],
      },
      {
        heading: "Sets",
        links: [
          { label: "Ethnic Sets", href: "/shop/ethnic-sets" },
          { label: "Piece Sets", href: "/shop/piece-sets" },
        ],
      },
    ],
  },
  {
    label: "Western",
    href: "/shop/western",
    columns: [
      {
        heading: "Shop Western",
        links: [
          { label: "Tops & Dresses", href: "/shop/tops" },
          { label: "Pants & Jeans", href: "/shop/pants" },
        ],
      },
    ],
  },
  { label: "Innerwear", href: "/shop/innerwear" },
];

export type Product = {
  name: string;
  price: number;
  mrp?: number;
  image: string;
  hoverImage?: string;
  href: string;
  tag?: string;
  category: string;
};

export type Category = {
  name: string;
  href: string;
  image: string;
  /* bento span — "big" is a 2x2 feature tile, "wide" spans two columns */
  span?: "big" | "wide";
};

/* Shop by Category (bento) — a curated selection pointing at the real shop
   pages. Order drives the bento's auto-placement so the grid tiles cleanly. */
export const categories: Category[] = [
  { name: "Sarees", href: "/shop/sarees", image: "/images/cat-ethnic-dress.jpg", span: "big" },
  { name: "Kurtis", href: "/shop/kurtis", image: "/images/cat-kurta.jpg" },
  { name: "Anarkalis", href: "/shop/anarkalis", image: "/images/cat-anarkali.jpg" },
  { name: "Piece Sets", href: "/shop/piece-sets", image: "/images/cat-kurta-sets.jpg" },
  { name: "Pants & Jeans", href: "/shop/pants", image: "/images/cat-bottomwear.jpg" },
  { name: "Tops & Dresses", href: "/shop/tops", image: "/images/cat-skirt-sets.jpg" },
  { name: "Shop All", href: "/shop/all", image: "/images/cat-shop-all.jpg" },
  { name: "Innerwear", href: "/shop/innerwear", image: "/images/cat-nighty.jpg", span: "wide" },
];

/* Why Delight Studio — the client's own words from the Brand Discovery form. */
export const whyIntro =
  "At Delight Studio, every dress is carefully selected with attention to detail, ensuring premium quality, timely delivery, and complete customer satisfaction.";

export type Pillar = { title: string; text: string; icon: "gem" | "truck" | "heart" | "tag" };

export const whyPillars: Pillar[] = [
  {
    title: "Premium Quality",
    text: "Every piece hand-picked with attention to detail — fabric, fit and finish you can trust.",
    icon: "gem",
  },
  {
    title: "Timely Delivery",
    text: "Carefully packed and dispatched on time, so your favourites reach you when you need them.",
    icon: "truck",
  },
  {
    title: "Customer Satisfaction",
    text: "Complete customer satisfaction is at the heart of everything we do at Delight Studio.",
    icon: "heart",
  },
  {
    title: "Moderate Price",
    text: "High-quality women's fashion at moderate, honest prices — style that feels effortless.",
    icon: "tag",
  },
];

/* Real contact details (Brand Discovery form). */
export const brand = {
  name: "Delight Studio",
  wordmark: "DELIGHT STUDIO",
  phone: "+91 90948 87777",
  phoneHref: "tel:+919094887777",
  email: "delightstudio3939@gmail.com",
  instagram: "https://www.instagram.com/delightstudio_chennai/",
  instagramHandle: "@delightstudio_chennai",
  address:
    "No 45/1, Kamarajar Salai, Mathiazhagan Nagar, Shanthi Nagar, Annamalai Colony, Chennai, Tamil Nadu 600093",
};

/* Footer link columns. */
export const footerShop: NavLink[] = [
  { label: "New Arrivals", href: "/shop/new" },
  { label: "Sarees", href: "/shop/sarees" },
  { label: "Ethnicwear", href: "/shop/ethnicwear" },
  { label: "Western", href: "/shop/western" },
  { label: "Innerwear", href: "/shop/innerwear" },
];

export const footerQuick: NavLink[] = [
  { label: "About Us", href: "/about" },
  { label: "Track Order", href: "/track-order" },
  { label: "Store Locator", href: "/stores" },
  { label: "Contact Us", href: "/contact" },
];

export const footerPolicies: NavLink[] = [
  { label: "Shipping Policy", href: "/shipping-policy" },
  { label: "Return & Exchange", href: "/returns" },
  { label: "Privacy Policy", href: "/privacy" },
  { label: "Terms & Conditions", href: "/terms" },
];

/* ============================================================
   SHOP CATALOG — real products from the client's stock export.
   The catalog array itself lives in lib/catalog.data.ts (generated).
   ============================================================ */

/* The client's stock uses standard S–XXL apparel sizing. A product's `sizes`
   array lists the sizes stocked; any ladder size not present renders greyed /
   "Not available" on the detail page. Sarees are one-size (`freeSize`). */
export const SIZE_LADDER = ["S", "M", "L", "XL", "XXL"] as const;
export type Size = (typeof SIZE_LADDER)[number];

export type CatalogProduct = Product & {
  slug: string;
  code: string; // original Excel item name — kept so the backend can match rows
  images: string[]; // gallery — [0] is the primary/card image
  types: string[]; // filter tags, e.g. ["Kalamkari"] or ["Crop Tops"]
  sizes: Size[]; // sizes currently in stock (subset of SIZE_LADDER)
  freeSize?: boolean; // sarees & one-size items — no size selection
  stock: number; // units available (0 = out of stock)
  fabric: string;
  color: string;
  description: string;
  rating: number;
  reviews: number;
  categorySlug: string; // leaf shop slug for the breadcrumb (e.g. "sarees")
  mrp: number;
};

export const catalog: CatalogProduct[] = CATALOG;

export function getCatalogProduct(slug: string): CatalogProduct | undefined {
  return catalog.find((p) => p.slug === slug);
}

export function productsByCategory(category: string): CatalogProduct[] {
  return catalog.filter((p) => p.category === category);
}

/* New Arrivals (homepage rail) — resolved from the generated slug list to real
   catalog products, so each card links to a live product-detail page. */
export const newArrivals: Product[] = NEW_ARRIVAL_SLUGS.map((s) => getCatalogProduct(s)).filter(
  (p): p is CatalogProduct => Boolean(p),
);

/* ============================================================
   SHOP PAGES — drives the dynamic route app/shop/[category].
   Each entry maps a URL slug to the display categories it shows,
   its Casio-style hero, and (for single-category pages) the filter
   type facets. Combined pages (new/ethnicwear/western) omit the
   type filter to keep the sidebar clean.
   ============================================================ */
export type ShopCategory = {
  slug: string;
  label: string; // short nav/breadcrumb label
  eyebrow: string;
  title: string; // hero title
  subtitle: string; // hero description
  image: string; // hero banner image
  categories: string[]; // display category names included
  facetKey?: string; // leaf slug in CATEGORY_FACETS (single-category pages)
};

export const shopCategories: ShopCategory[] = [
  {
    slug: "new",
    label: "New Arrivals",
    eyebrow: "Just In",
    title: "New Arrivals",
    subtitle:
      "The latest additions to the Delight Studio wardrobe — fresh sarees, kurtis, western and more, straight from the studio floor.",
    image: "/images/hero.jpg",
    categories: [
      "Sarees",
      "Kurti",
      "Anarkali",
      "Ethnic Set",
      "Piece Set",
      "Western",
      "Pants",
      "Innerwear",
    ],
  },
  {
    slug: "all",
    label: "All Products",
    eyebrow: "The Full Collection",
    title: "All Products",
    subtitle:
      "Every piece in the Delight Studio wardrobe — sarees, kurtis, anarkalis, sets, western and innerwear, all in one place.",
    image: "/images/hero.jpg",
    categories: [
      "Sarees",
      "Kurti",
      "Anarkali",
      "Ethnic Set",
      "Piece Set",
      "Western",
      "Pants",
      "Innerwear",
    ],
  },
  {
    slug: "sarees",
    label: "Sarees",
    eyebrow: "The Saree Edit",
    title: "Sarees",
    subtitle:
      "From feather-light cottons to statement silks — ninety-plus drapes, handpicked in Chennai for every occasion.",
    image: "/images/cat-ethnic-dress.jpg",
    categories: ["Sarees"],
    facetKey: "sarees",
  },
  {
    slug: "ethnicwear",
    label: "Ethnicwear",
    eyebrow: "The Ethnic Edit",
    title: "Ethnicwear",
    subtitle: "Kurtis, anarkalis and coordinated suit sets for every celebration.",
    image: "/images/cat-kurta-sets.jpg",
    categories: ["Kurti", "Anarkali", "Ethnic Set", "Piece Set"],
  },
  {
    slug: "kurtis",
    label: "Kurtis",
    eyebrow: "Everyday Ethnic",
    title: "Kurtis",
    subtitle: "Easy, breathable kurtis — straight, A-line and embroidered for daily wear.",
    image: "/images/cat-kurta.jpg",
    categories: ["Kurti"],
    facetKey: "kurtis",
  },
  {
    slug: "anarkalis",
    label: "Anarkalis",
    eyebrow: "Festive",
    title: "Anarkalis",
    subtitle: "Flared, floor-sweeping silhouettes for the occasions that matter.",
    image: "/images/cat-anarkali.jpg",
    categories: ["Anarkali"],
    facetKey: "anarkalis",
  },
  {
    slug: "ethnic-sets",
    label: "Ethnic Sets",
    eyebrow: "Coordinated",
    title: "Ethnic Sets",
    subtitle: "Ready-to-wear ethnic suits, thoughtfully put together.",
    image: "/images/cat-skirt-sets.jpg",
    categories: ["Ethnic Set"],
    facetKey: "ethnic-sets",
  },
  {
    slug: "piece-sets",
    label: "Piece Sets",
    eyebrow: "Ready Sets",
    title: "Piece Sets",
    subtitle: "Two-piece and three-piece sets that make dressing effortless.",
    image: "/images/cat-kurta-sets.jpg",
    categories: ["Piece Set"],
    facetKey: "piece-sets",
  },
  {
    slug: "western",
    label: "Western",
    eyebrow: "The Western Line",
    title: "Western",
    subtitle: "Tops, dresses, gowns and denim for off-duty days.",
    image: "/images/cat-shop-all.jpg",
    categories: ["Western", "Pants"],
  },
  {
    slug: "tops",
    label: "Tops & Dresses",
    eyebrow: "Off-Duty",
    title: "Tops & Dresses",
    subtitle: "Crop tops, shirts, kaftans and easy dresses for everyday style.",
    image: "/images/p1.jpg",
    categories: ["Western"],
    facetKey: "tops",
  },
  {
    slug: "pants",
    label: "Pants & Jeans",
    eyebrow: "Bottoms",
    title: "Pants & Jeans",
    subtitle: "Denim, palazzos and kurta pants cut for all-day comfort.",
    image: "/images/cat-bottomwear.jpg",
    categories: ["Pants"],
    facetKey: "pants",
  },
  {
    slug: "innerwear",
    label: "Innerwear",
    eyebrow: "Essentials",
    title: "Innerwear",
    subtitle: "Everyday comfort basics — camisoles, slips and bras.",
    image: "/images/cat-nighty.jpg",
    categories: ["Innerwear"],
    facetKey: "innerwear",
  },
];

/* Hero slider images per shop page (placeholder stock for now — swap for the
   client's real banners later). The category hero rotates through these. */
export const heroSlides: Record<string, string[]> = {
  new: ["/images/hero.jpg", "/images/cat-shop-all.jpg", "/images/p2.jpg"],
  sarees: ["/images/cat-ethnic-dress.jpg", "/images/p3.jpg", "/images/cat-skirt-sets.jpg"],
  ethnicwear: ["/images/cat-kurta-sets.jpg", "/images/cat-kurta.jpg", "/images/cat-anarkali.jpg"],
  kurtis: ["/images/cat-kurta.jpg", "/images/p1.jpg", "/images/cat-kurta-sets.jpg"],
  anarkalis: ["/images/cat-anarkali.jpg", "/images/p3.jpg", "/images/cat-ethnic-dress.jpg"],
  "ethnic-sets": ["/images/cat-skirt-sets.jpg", "/images/cat-kurta-sets.jpg", "/images/p4.jpg"],
  "piece-sets": ["/images/cat-kurta-sets.jpg", "/images/cat-skirt-sets.jpg", "/images/p5.jpg"],
  western: ["/images/cat-shop-all.jpg", "/images/p1.jpg", "/images/p6.jpg"],
  tops: ["/images/p1.jpg", "/images/p6.jpg", "/images/cat-shop-all.jpg"],
  pants: ["/images/cat-bottomwear.jpg", "/images/p4.jpg", "/images/p5.jpg"],
  innerwear: ["/images/cat-nighty.jpg", "/images/cat-shop-all.jpg", "/images/p2.jpg"],
};

export function heroSlidesFor(slug: string): string[] {
  const slides = heroSlides[slug];
  if (slides && slides.length) return slides;
  const cfg = getShopCategory(slug);
  return cfg ? [cfg.image] : ["/images/hero.jpg"];
}

export function getShopCategory(slug: string): ShopCategory | undefined {
  return shopCategories.find((c) => c.slug === slug);
}

/* Products for a shop page — filtered by its display categories, keeping the
   catalog's authored order. */
export function productsForShop(slug: string): CatalogProduct[] {
  const cfg = getShopCategory(slug);
  if (!cfg) return [];
  // "New" lists only the tagged new-arrival items (the whole store lives under
  // /shop/all), preserving the NEW_ARRIVAL_SLUGS order.
  if (slug === "new") {
    return NEW_ARRIVAL_SLUGS.map((s) => getCatalogProduct(s)).filter(
      (p): p is CatalogProduct => Boolean(p),
    );
  }
  const set = new Set(cfg.categories);
  return catalog.filter((p) => set.has(p.category));
}

/* Filter type facets for a shop page (empty for combined pages → no Type filter). */
export function facetsForShop(slug: string): string[] {
  const cfg = getShopCategory(slug);
  if (!cfg?.facetKey) return [];
  return CATEGORY_FACETS[cfg.facetKey] ?? [];
}
